apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: node-exporter
    application: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app: node-exporter
  sessionAffinity: None
  type: ClusterIP
