apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /exports/grafana
    server: sgitmaster1fe.scigames.at
  persistentVolumeReclaimPolicy: Recycle
