apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /exports/prometheus
    server: sgitmaster1fe.scigames.at
  persistentVolumeReclaimPolicy: Recycle
